"use client";

import { useState } from "react";
import { motion, useReducedMotion } from "motion/react";
import { ArrowDownRight, ArrowUpRight, ChevronRight, Code2, Database, GitBranch, Link, Mail, Menu, X } from "lucide-react";
import { projects, secondaryProjects } from "@/data/portfolio";

const links = [{ label: "About", href: "#about" }, { label: "Experience", href: "#experience" }, { label: "Projects", href: "#projects" }, { label: "Contact", href: "#contact" }];

function SectionIntro({ index, eyebrow, title, copy }: { index: string; eyebrow: string; title: string; copy?: string }) {
  return <div className="grid gap-7 md:grid-cols-12 md:gap-6"><p className="font-mono text-[10px] uppercase tracking-[.18em] text-[#6d756d] md:col-span-2">{index} / {eyebrow}</p><div className="md:col-span-7"><h2 className="font-display text-4xl font-medium tracking-[-.055em] md:text-6xl">{title}</h2>{copy && <p className="mt-5 max-w-xl text-base leading-7 text-[#566058] md:text-lg">{copy}</p>}</div></div>;
}

export function Portfolio() {
  const [open, setOpen] = useState(false);
  const reduce = useReducedMotion();
  const reveal = reduce ? {} : { initial: { opacity: 0, y: 18 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: .15 }, transition: { duration: .55 } };
  return <main className="page-grid overflow-hidden">
    <nav className="sticky top-0 z-30 mx-auto flex h-16 max-w-[1440px] items-center justify-between border-b border-[#d7d4cb]/90 bg-[#f4f1e9]/90 px-5 backdrop-blur-md md:px-10">
      <a href="#top" className="font-display text-sm font-semibold tracking-[-.04em]">AB<span className="text-[#eb4c2e]">.</span></a>
      <div className="hidden items-center gap-7 md:flex">{links.map(link => <a key={link.label} href={link.href} className="font-mono text-[10px] uppercase tracking-[.15em] text-[#596259] transition-colors hover:text-[#eb4c2e]">{link.label}</a>)}</div>
      <div className="hidden items-center gap-4 md:flex"><a href="https://github.com/Adit2020" target="_blank" rel="noreferrer" aria-label="GitHub"><GitBranch size={16}/></a><a href="#contact" className="flex items-center gap-1 font-mono text-[10px] uppercase tracking-[.14em] text-[#eb4c2e]">Let&apos;s talk <ArrowUpRight size={13}/></a></div>
      <button onClick={() => setOpen(!open)} aria-label="Toggle navigation" aria-expanded={open} className="md:hidden">{open ? <X size={21}/> : <Menu size={21}/>}</button>
      {open && <div className="absolute left-0 top-16 flex w-full flex-col border-b border-[#d7d4cb] bg-[#f4f1e9] px-5 py-5 md:hidden">{links.map(link => <a key={link.label} onClick={() => setOpen(false)} href={link.href} className="py-3 font-display text-2xl tracking-[-.04em]">{link.label}</a>)}</div>}
    </nav>

    <section id="top" className="grid-fade mx-auto min-h-[calc(100svh-4rem)] max-w-[1440px] px-5 pb-12 pt-12 md:px-10 md:pt-20">
      <motion.div {...reveal} className="grid min-h-[calc(100svh-12rem)] content-between gap-12 md:grid-cols-12">
        <div className="md:col-span-8"><div className="mb-8 flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.17em] text-[#657066]"></div><h1 className="font-display max-w-5xl text-[clamp(3.7rem,8.2vw,8.2rem)] font-medium leading-[.87] tracking-[-.075em]">Aditya Bhosale<span className="text-[#eb4c2e]">.</span></h1><p className="mt-8 max-w-2xl text-xl leading-8 tracking-[-.025em] text-[#445047] md:text-2xl md:leading-9">Software engineer in training, building <em className="font-normal text-[#eb4c2e]">intelligent systems</em>, developer tools, and data products that make complicated work feel clear.</p></div>
        <div className="flex flex-col justify-between border-t border-[#d7d4cb] pt-5 md:col-span-3 md:col-start-10 md:border-t-0 md:border-l md:pl-6 md:pt-1"><p className="font-mono text-[10px] leading-5 uppercase tracking-[.14em] text-[#657066]">Computer Science & Engineering<br/>The Ohio State University<br/>Class of 2028</p><a href="#projects" className="mt-10 flex items-center gap-2 text-sm font-medium transition-colors hover:text-[#eb4c2e]">Explore selected work <ArrowDownRight size={17}/></a></div>
        <div className="col-span-full grid grid-cols-2 border-t border-[#d7d4cb] sm:grid-cols-4">{[["Focus","AI & systems"],["Based in","Columbus, OH"],["Currently","Building agents"],["Previously","Cintas"]].map(([a,b], i) => <div key={a} className={`py-4 ${i ? "border-l border-[#d7d4cb] pl-4" : ""} ${i === 3 ? "hidden sm:block" : ""}`}><p className="font-mono text-[10px] uppercase tracking-[.13em] text-[#697268]">{a}</p><p className="mt-1 text-sm">{b}</p></div>)}</div>
      </motion.div>
    </section>

    <section id="about" className="section-rule mx-auto max-w-[1440px] px-5 py-24 md:px-10 md:py-36"><motion.div {...reveal}><SectionIntro index="01" eyebrow="A little context" title="I like the messy part before a system becomes obvious." copy="I’m drawn to projects where software has to listen, decide, and coordinate—whether that means making an agent understand a codebase, extracting signal from social posts, or making an enterprise workflow respond in seconds."/><div className="mt-16 grid gap-px bg-[#d7d4cb] md:grid-cols-3">{[[Code2,"Build with intent","Architecture, interfaces, and the small details that turn a solution into useful software."],[Database,"Find the signal","Pipelines that make messy, real-world information searchable and trustworthy."],[ArrowUpRight,"Make systems move","Automation and feedback loops that replace slow, manual operations with momentum."]].map(([Icon,title,copy]) => { const FeatureIcon = Icon as typeof Code2; return <div key={title as string} className="bg-[#f4f1e9] p-6"><FeatureIcon size={21} strokeWidth={1.5}/><p className="mt-12 font-display text-xl tracking-[-.04em]">{title as string}</p><p className="mt-3 text-sm leading-6 text-[#5c665d]">{copy as string}</p></div>})}</div></motion.div></section>

    <section id="experience" className="section-rule bg-[#172019] text-[#f4f1e9]"><div className="mx-auto max-w-[1440px] px-5 py-24 md:px-10 md:py-36"><motion.div {...reveal} className="grid gap-8 md:grid-cols-12"><div className="md:col-span-2"><p className="font-mono text-[10px] uppercase tracking-[.18em] text-[#aeb8ad]">02 / Experience</p></div><div className="md:col-span-9"><p className="font-mono text-[10px] uppercase tracking-[.15em] text-[#aeb8ad]">2025 — Cintas · Information Technology Intern</p><h2 className="mt-5 max-w-4xl font-display text-4xl leading-[.95] tracking-[-.055em] md:text-6xl">Software that kept critical workflows from waiting.</h2><div className="mt-14 grid gap-10 border-t border-[#425148] pt-7 md:grid-cols-2"><div><p className="text-4xl tracking-[-.06em] text-[#eb4c2e]">45 min → seconds</p><p className="mt-4 max-w-sm text-sm leading-6 text-[#c4ccc4]">Redesigned event-processing logic for emergency and change-request notifications, validating the new workflow in production-like environments.</p></div><div><p className="font-display text-2xl tracking-[-.04em]">A living organization map</p><p className="mt-4 max-w-sm text-sm leading-6 text-[#c4ccc4]">Helped lead a cloud-hosted organizational visualization application, giving teams a shared view of ownership and reporting relationships.</p><p className="mt-5 font-mono text-[10px] uppercase tracking-[.13em] text-[#aeb8ad]">React Flow · Node.js · REST · MySQL · GitLab CI/CD</p></div></div></div></motion.div></div></section>

    <section id="projects" className="section-rule mx-auto max-w-[1440px] px-5 py-24 md:px-10 md:py-36"><motion.div {...reveal}><SectionIntro index="03" eyebrow="Selected work" title="Projects with a point of view." copy="A few systems I’m building at the intersection of software, automation, and machine intelligence."/></motion.div><div className="mt-20 flex flex-col gap-20">{projects.map(project => <motion.article {...reveal} key={project.number} className="grid gap-8 border-t border-[#d7d4cb] pt-5 md:grid-cols-12"><div className="md:col-span-2"><p className="font-mono text-[10px] uppercase tracking-[.16em] text-[#697268]">{project.number} / {project.type}</p></div><div className="md:col-span-5"><h3 className="whitespace-pre-line font-display text-4xl leading-[.94] tracking-[-.06em] md:text-6xl">{project.name}</h3><p className="mt-7 max-w-md text-base leading-7 text-[#526057]">{project.summary}</p><div className="mt-8 flex flex-wrap gap-x-4 gap-y-2">{project.tags.map(tag => <span key={tag} className="font-mono text-[10px] uppercase tracking-[.13em] text-[#657066]">{tag}</span>)}</div></div><div className="md:col-span-4 md:col-start-9"><div className="relative overflow-hidden border border-[#d7d4cb] bg-[#eeece4] p-5"><div className="absolute left-0 top-0 h-1 w-full" style={{background: project.color}}/><p className="font-mono text-[10px] uppercase tracking-[.14em] text-[#697268]">System sketch</p><div className="mt-8 flex flex-col gap-2">{project.nodes.map((node, n) => <div key={node} className="flex items-center gap-2"><span className="flex size-6 items-center justify-center rounded-full border border-[#bfc4bd] bg-[#f4f1e9] font-mono text-[9px]" style={{borderColor: n === project.nodes.length - 1 ? project.color : undefined}}>{n + 1}</span><div className="h-px flex-1 bg-[#cdd0c9]"/><span className="w-24 font-mono text-[10px] uppercase tracking-[.1em] text-[#4e5b52]">{node}</span></div>)}</div><p className="mt-8 border-t border-[#d7d4cb] pt-4 text-xs leading-5 text-[#59645b]">{project.detail}</p></div><a href="#contact" className="mt-5 inline-flex items-center gap-1 text-sm font-medium hover:text-[#eb4c2e]">Discuss the system <ArrowUpRight size={15}/></a></div></motion.article>)}</div></section>

    <section className="section-rule mx-auto max-w-[1440px] px-5 py-24 md:px-10"><div className="grid gap-8 md:grid-cols-12"><p className="font-mono text-[10px] uppercase tracking-[.17em] text-[#697268] md:col-span-2">04 / Elsewhere</p><div className="md:col-span-10">{secondaryProjects.map(([name, category, desc]) => <a key={name} href="#contact" className="group grid gap-3 border-t border-[#d7d4cb] py-5 transition-colors hover:text-[#eb4c2e] md:grid-cols-12"><p className="font-display text-2xl tracking-[-.045em] md:col-span-5">{name}</p><p className="font-mono text-[10px] uppercase tracking-[.13em] text-[#697268] md:col-span-2">{category}</p><p className="text-sm leading-6 text-[#59645b] md:col-span-4">{desc}</p><ChevronRight className="hidden justify-self-end md:block" size={18}/></a>)}</div></div></section>

    <section id="contact" className="bg-[#eb4c2e] text-white"><div className="mx-auto max-w-[1440px] px-5 py-24 md:px-10 md:py-32"><p className="font-mono text-[10px] uppercase tracking-[.17em] text-white/75">05 / Contact</p><div className="mt-10 grid gap-10 md:grid-cols-12"><h2 className="font-display text-[clamp(3.6rem,8vw,7.5rem)] leading-[.86] tracking-[-.075em] md:col-span-8">Let&apos;s build something with teeth.</h2><div className="flex flex-col justify-end gap-6 md:col-span-3 md:col-start-10"><p className="text-base leading-7 text-white/85">I&apos;m always up for a conversation about interesting engineering problems, product ideas, and internships.</p><a href="https://www.linkedin.com/in/aditya-bhosale-17400026b/" target="_blank" rel="noreferrer" className="flex items-center justify-between border-b border-white/50 pb-3 text-sm font-medium">Connect on LinkedIn <Link size={16}/></a><a href="https://github.com/Adit2020" target="_blank" rel="noreferrer" className="flex items-center justify-between border-b border-white/50 pb-3 text-sm font-medium">See my GitHub <GitBranch size={16}/></a><a href="mailto:adityabhosale@gmail.com" className="flex items-center justify-between border-b border-white/50 pb-3 text-sm font-medium">Send an email <Mail size={16}/></a></div></div><footer className="mt-24 flex flex-col justify-between gap-3 border-t border-white/35 pt-5 font-mono text-[10px] uppercase tracking-[.13em] text-white/70 sm:flex-row"><span>© {new Date().getFullYear()} Aditya Bhosale</span><span>Designed & built with intent</span></footer></div></section>
  </main>;
}
